% clear
clc,clear,close all

I = imread('..\exp\img\alphabet2.jpg');
udata=[0 266];
vdata=[0 245];
tform=maketform('projective',[0 0;223 0; 245 266; 0 223],...
                            [0 0;245 0; 245 266; 0 266]);
                            [B,xdata,ydata] = imtransform(I,tform,'bicubic', ...
                            'udata',udata,...
                            'vdata',vdata,...
                            'size',size(I),...
                            'fill',128);
subplot(1,2,1); imshow(I,'XData',udata,'YData',vdata)
subplot(1,2,2); imshow(B,'XData',xdata,'YData',ydata)